name: alebrew
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  bloc: ^3.0.0
  http: ^0.12.0+4
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0
  build_runner: ^1.7.3

flutter:
  uses-material-design: true
